if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
  source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
else
  # self-bootstrap the plugins on first start
  if command -v git > /dev/null; then
    echo "cloning zsh plugins into ~/.zsh/plugins..."
    mkdir -p ~/.zsh/plugins
    (
      cd ~/.zsh/plugins || exit
      git clone -q https://github.com/mafredri/z -b zsh-flock
      git clone -q https://github.com/chriskempson/base16-shell
      git clone -q https://github.com/hlissner/zsh-autopair
      git clone -q https://github.com/romkatv/gitstatus
      git clone -q https://github.com/zdharma-continuum/fast-syntax-highlighting
      git clone -q https://github.com/romkatv/zsh-defer
    )
  fi

  if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
    source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
  else
    echo "zsh-defer is missing!"
    echo "you'll get some errors below..."
    echo
  fi
fi

# load files
files=(
  options
  completion
  locale
  muninn
  aliases
  functions
  history
  bindkeys
  terminal
  fzf
  colors
  prompt
  plugins
)

if [ "$(uname)" = "Darwin" ]; then
  source ~/.zsh/darwin.zsh
fi

for file in $files; do
  source ~/.zsh/$file.zsh
done

# ssh/mosh dynamic motd
if (( $+commands[motd] )); then
  if [[ -n "$SSH_TTY" && "$(tty)" = "$SSH_TTY" ]] || [[ "$(ps -o comm= -p $PPID 2>/dev/null)" = *mosh-server* ]]; then
    motd
  fi
fi

