if [ -f ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh ]; then
  source ~/.zsh/plugins/zsh-defer/zsh-defer.plugin.zsh
else
  echo "zsh-defer is missing! run \`setup.sh\`"
  echo "you'll get some errors below..."
  echo
fi

# load files
files=(
  options
  completion
  locale
  muninn
  aliases
  functions
  history
  bindkeys
  terminal
  fzf
  colors
  prompt
  plugins
)

if [ "$(uname)" = "Darwin" ]; then
  source ~/.zsh/darwin.zsh
fi

for file in $files; do
  source ~/.zsh/$file.zsh
done

# ssh motd
if [[ -n "$SSH_TTY" && "$(tty)" = "$SSH_TTY" ]] && (( $+commands[motd] )); then
  motd
fi

