#!/usr/bin/env bash

# should contain
# PUSHOVER_TOKEN=...
# PUSHOVER_USER=...
source ~/.pushoverrc

curl -s -F "token=$PUSHOVER_TOKEN" -F "user=$PUSHOVER_USER" -F "message=$*" https://api.pushover.net/1/messages.json > /dev/null

