#!/usr/bin/env bash

PACKAGES=(
  "alfred-infinite-clipboard"
  "logger-search"
  "muninn-cli"
  "muninn-get-asset"
  "muninn-make-month"
  "name-pdfs"
  "timav-cli"
)

for dir in "${PACKAGES[@]}"; do
  pushd "$HOME/Documents/Projects/$dir" || exit
  npm install
  npm link
  popd || exit
done
