#!/usr/bin/env node

const units = {
  w: 604800,
  d: 86400,
  h: 3600,
  m: 60,
  s: 1,
};

const input = process.argv
  .slice(2)
  .join("")
  .replace(/([wdhms])[a-z]*/g, "$1")
  .replace(/[^wdhms\d]/g, "");

let total = 0;
let matched = false;

for (const [, n, u] of input.matchAll(/(\d+)([wdhms])/g)) {
  total += parseInt(n) * units[u];
  matched = true;
}

if (!matched) {
  process.stderr.write(
    "Usage: seconds [Xw][Xd][Xh][Xm][Xs]  e.g. seconds 2h30m\n",
  );

  process.exit(1);
}

process.stdout.write(String(total) + "\n");
