#!/usr/bin/env bash

# disable the "accents" menu on keyboard key held
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# disable Finder animations
defaults write com.apple.finder DisableAllAnimations -bool true

# disable focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# increase window resize speed
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# set the icon size of Dock items
defaults write com.apple.dock tilesize -int 48

# lock Dock size
defaults write com.apple.dock size-immutable -bool true

# show/hide Dock without delay
defaults write com.apple.dock autohide-delay -float 0

# save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# save screenshots to Dropbox
defaults write com.apple.screencapture location ~/Documents/Dropbox/Screenshots/

# name screenshots as Screenshot...
defaults write com.apple.screencapture name "Screenshot"

echo "$(tput setaf 1)done, note that some of these changes require app restart or logout to take effect...$(tput sgr0)"

