#!/usr/bin/env bash
#
# used with crontab:
# ```
# @reboot ./bin/tmux-daemon
# ```

HOSTNAME="$(hostname)"

if [[ $HOSTNAME == "berry" ]]; then
  SHELL=/usr/bin/bash tmux -u new-session -d -s "friday"
  tmux send-keys "cd ~/friday" "C-m"
  tmux send-keys "nvm use && npm start" "C-m"
fi
