#!/usr/bin/env bash

args=()
while [ $# -gt 0 ]; do
  case "$1" in
    -d)
      args+=(-c "$2")
      shift 2
      ;;
    *)
      args+=("$1")
      shift
      ;;
  esac
done

width=$(tmux display-message -p '#{pane_width}')
height=$(tmux display-message -p '#{pane_height}')

# terminal characters are roughly 1:2 aspect ratio, a ratio of 2.8 means the
# pane is significantly wider than it is tall
if [ $(( width * 10 )) -gt $(( height * 28 )) ]; then
  # Split left/right
  tmux split-window -h "${args[@]}"
else
  # Split top/bottom
  tmux split-window -v "${args[@]}"
fi
