#!/usr/bin/env bash

function gitUpdate {
  if [ -d "$*" ]; then
    pushd "$*" > /dev/null || return

    if [ -e .git ]; then
      echo -e "$(tput setaf 2)Checking $(basename "$*")...$(tput sgr0)"
      git pull
      echo
    fi

    popd > /dev/null || return
  fi
}

if [[ $(hostname -s) == "Orchid" ]]; then
  echo -e "$(tput setaf 2)Checking Nix...$(tput sgr0)"
  pushd ~/.config/home-manager > /dev/null || return
  # sudo nix upgrade-nix
  nix flake update
  home-manager switch --flake .#szymon@orchid
  echo
  popd > /dev/null || return
fi

if [[ $(hostname -s) == "szymon-vm" ]]; then
  echo -e "$(tput setaf 2)Checking Nix...$(tput sgr0)"
  pushd ~/.config/home-manager > /dev/null || return
  nix run home-manager -- switch --flake .#szymon@devvm
  echo
  popd > /dev/null || return
fi

if [ -d ~/.zsh/plugins ]; then
  for i in ~/.zsh/plugins/*; do
    gitUpdate "$i"
  done
fi

if [ -d ~/.tmux/plugins ]; then
  for i in ~/.tmux/plugins/*; do
    gitUpdate "$i"
  done
fi

if hash ncu 2> /dev/null; then
  echo -e "$(tput setaf 2)Checking NPM...$(tput sgr0)"

  packages=$(ncu -g --format lines)

  if [ -n "$packages" ]; then
    npm i -g $packages
    echo
  else
    echo "Nothing to do!"
    echo
  fi
fi

if hash vale 2> /dev/null; then
  pushd ~/ > /dev/null || return
  echo -e "$(tput setaf 2)Checking Vale...$(tput sgr0)"
  vale sync
  popd > /dev/null || return
fi
