{
  config,
  pkgs,
  lib,
  repoRoot,
  ...
}:
let
  dotfileDir = "${repoRoot}/dotfiles";
  link = config.lib.file.mkOutOfStoreSymlink;
  mqtt = import ../../mqtt.nix;
  ports = import ./ports.nix;
  inherit (import ./lib.nix { inherit pkgs lib; }) waitForMosquitto mkProjectService mkTimer;
in
{
  imports = [
    ../../common.nix
    ./home/neolink.nix
  ];

  home.homeDirectory = "/home/szymon";

  sops.defaultSopsFile = ../../secrets/minix.yaml;
  sops.age.keyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt";

  sops.secrets = {
    claude_oauth_token = { };
    smartbox_email = { };
    smartbox_password = { };
    archivist_pinterest_email = { };
    archivist_pinterest_password = { };
    archivist_pinboard_api_key = { };
    archivist_arena_access_token = { };
    smtp_host = { };
    smtp_bot_email = { };
    smtp_bot_password = { };
    gemini_api_key_property_search = { };
    pushover_token_user = { };
  }
  //
    lib.genAttrs
      [
        "gemini_api_key_opencode"
        "pushover_user"
        "timav_google_client_id"
        "timav_google_client_secret"
        "timav_google_project_id"
      ]
      (_: {
        sopsFile = ../../secrets/shared.yaml;
      });

  # token generated by `claude setup-token`
  sops.templates."claude-oauth-token" = {
    path = "${config.home.homeDirectory}/.claude/long-lived-oauth-token";
    content = config.sops.placeholder.claude_oauth_token;
  };

  sops.templates."gemini-api-key" = {
    path = "${config.home.homeDirectory}/.config/opencode/gemini_api_key";
    content = config.sops.placeholder.gemini_api_key_opencode;
  };

  sops.templates."smartbox2mqtt-config" = {
    path = "${config.home.homeDirectory}/.config/smartbox2mqtt/config.json";
    content = builtins.toJSON {
      smartbox = {
        username = config.sops.placeholder.smartbox_email;
        password = config.sops.placeholder.smartbox_password;
        apiName = "api-hjm";
      };
      mqtt = {
        host = mqtt.host;
        port = mqtt.port;
        username = mqtt.username;
        password = mqtt.password;
        baseTopic = "friday/hjm";
      };
    };
  };

  # engine config (no secrets: mqtt creds come from mqtt.nix)
  xdg.configFile."friday-ruler/config.json".text = builtins.toJSON {
    host = mqtt.host;
    port = mqtt.port;
    username = mqtt.username;
    password = mqtt.password;
    topicPrefix = "friday/ruler";
  };

  # user config (pushover secrets, router + location)
  sops.templates."friday-ruler-user-config" = {
    path = "${config.home.homeDirectory}/.config/friday-ruler/user.json";
    content = builtins.toJSON {
      pushover = {
        token = config.sops.placeholder.pushover_token_user;
        user = config.sops.placeholder.pushover_user;
      };
      router = {
        host = "192.168.1.1";
        username = "admin";
        privateKeyPath = "${config.home.homeDirectory}/.ssh/id_ed25519";
      };
      location = {
        lat = 52.4069;
        lon = 16.9299;
      };
    };
  };

  sops.templates."archivist-config" = {
    path = "${config.home.homeDirectory}/.config/archivist/config.json";
    content = builtins.toJSON {
      pinterest = {
        loginMethod = "password";
        profile = "szymon_k";
        username = config.sops.placeholder.archivist_pinterest_email;
        password = config.sops.placeholder.archivist_pinterest_password;
        appendOnly = true;
      };
      pinboard = {
        apiKey = config.sops.placeholder.archivist_pinboard_api_key;
      };
      arena = {
        userId = 52291;
        accessToken = config.sops.placeholder.archivist_arena_access_token;
      };
      screenshot = {
        directory = "${config.home.homeDirectory}/.dropbox-hm/Dropbox/Screenshots";
      };
    };
  };

  sops.templates."msmtp-config" = {
    path = "${config.home.homeDirectory}/.config/msmtp/config";
    content = ''
      defaults
      tls on
      port 587

      account default
      host ${config.sops.placeholder.smtp_host}
      from ${config.sops.placeholder.smtp_bot_email}
      auth on
      user ${config.sops.placeholder.smtp_bot_email}
      password ${config.sops.placeholder.smtp_bot_password}
    '';
  };

  sops.templates."property-search-config.json" = {
    path = "${config.home.homeDirectory}/.config/property-search/config.json";
    content = builtins.toJSON {
      smtp = {
        host = config.sops.placeholder.smtp_host;
        port = 587;
        user = config.sops.placeholder.smtp_bot_email;
        pass = config.sops.placeholder.smtp_bot_password;
      };
      email = {
        from = "Property Search Bot <${config.sops.placeholder.smtp_bot_email}>";
        to = "hi@szymonkaliski.com";
      };
      gemini = {
        apiKey = config.sops.placeholder.gemini_api_key_property_search;
      };
    };
  };

  sops.templates."pushoverrc" = {
    path = "${config.home.homeDirectory}/.pushoverrc";
    content = ''
      PUSHOVER_TOKEN=${config.sops.placeholder.pushover_token_user}
      PUSHOVER_USER=${config.sops.placeholder.pushover_user}
    '';
  };

  home.packages = [
    pkgs.chromium
    pkgs.dnsutils
    pkgs.lm_sensors
    pkgs.trash-cli
  ];

  home.file.".config/rss2email.cfg".source = link "${dotfileDir}/rss2email.cfg";

  xdg.configFile."lgtv2mqtt2/lgtv.json".source = link "${dotfileDir}/lgtv2mqtt2/lgtv.json";

  xdg.configFile."lgtv2mqtt2/mqtt.json".text = builtins.toJSON {
    host = mqtt.host;
    username = mqtt.username;
    password = mqtt.password;
  };

  xdg.configFile."xiaomiclock2mqtt/config.json".text = builtins.toJSON {
    ble = {
      mac = "A4:C1:38:B3:76:F7";
    };
    mqtt = {
      host = mqtt.host;
      port = mqtt.port;
      username = mqtt.username;
      password = mqtt.password;
      baseTopic = "friday/sensor_living_room_temperature";
    };
  };

  services.dropbox.enable = true;

  # keep a default "home" tmux session alive. ExecStart creates it then blocks
  # until it is closed; Restart=always then re-runs ExecStart to recreate it, so
  # closing the home session (not just killing the whole server) brings it back.
  # telegraphist relies on home always existing and never creates it itself.
  #
  # the tmux server daemonizes into this unit's cgroup, so the default
  # KillMode=control-group would SIGKILL the whole server (every session) on each
  # restart. KillMode=process limits the kill to the blocking loop, leaving the
  # server and any other sessions alive; recreating home thus never touches them.
  # for the same reason there is no `kill-server` ExecStop.
  #
  # has-session is targeted as "=home" (the `=` forces an exact match); a plain
  # `-t home` prefix-matches any home* session (e.g. home-configuration), so the
  # loop would never notice home itself being closed.
  systemd.user.services.tmux = {
    Unit = {
      Description = "tmux default session";
      # don't restart on rebuild (kills running sessions)
      X-SwitchMethod = "keep-old";
    };
    Service = {
      ExecStart = "${pkgs.zsh}/bin/zsh -lc '${pkgs.tmux}/bin/tmux new-session -d -s home 2>/dev/null; while ${pkgs.tmux}/bin/tmux has-session -t \"=home\" 2>/dev/null; do ${pkgs.coreutils}/bin/sleep 5; done'";
      KillMode = "process";
      Restart = "always";
      RestartSec = 1;
    };
    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.dropbox.Unit.OnFailure = [ "notify-failure@%N.service" ];

  systemd.user.services."notify-failure@" = {
    Unit.Description = "Failure notification for %i";
    Service = {
      Type = "oneshot";
      # wait for possible restart, skip if service recovered
      ExecStartPre = "${pkgs.coreutils}/bin/sleep 5";
      ExecCondition = "${pkgs.bash}/bin/bash -c '! ${pkgs.systemd}/bin/systemctl --user is-active --quiet %i'";
      ExecStart = "-${pkgs.bash}/bin/bash -c '%h/.bin/notify-pushover \"Failed: %i\"'";
      Environment = "PATH=${pkgs.bash}/bin:${pkgs.coreutils}/bin:${pkgs.curl}/bin";
    };
  };

  systemd.user.services.smartbox2mqtt = mkProjectService {
    dir = "smartbox2mqtt";
    description = "Smartbox to MQTT bridge for heaters";
    extraUnits = [ "sops-nix.service" ];
    needsMqtt = true;
    command = "node src/index.js";
  };

  systemd.user.services.lgtv2mqtt2 = mkProjectService {
    dir = "lgtv2mqtt2";
    description = "LG TV to MQTT bridge";
    needsMqtt = true;
    command = "node cli.js";
  };

  # homebridge exits 143 (SIGTERM) on clean stop
  systemd.user.services.friday-homebridge = mkProjectService {
    dir = "friday-homebridge";
    description = "Homebridge";
    needsMqtt = true;
    build = "npm run pre-run";
    command = "npx homebridge -I";
    successExitStatus = "143";
    timeoutStop = 10;
  };

  systemd.user.services.boot-notify = {
    Unit = {
      Description = "Boot notification";
      After = [
        "default.target"
        "network-online.target"
      ];
      Wants = [ "network-online.target" ];
      ConditionPathExists = "!/run/user/%U/boot-notify-done";
    };

    Service = {
      Type = "oneshot";
      ExecStart =
        let
          bootNotify = pkgs.writeShellScript "boot-notify" ''
            booted=$(${pkgs.coreutils}/bin/readlink -f /run/booted-system)
            ver=$(${pkgs.coreutils}/bin/cat /run/booted-system/nixos-version 2>/dev/null || echo "?")
            gen=""
            for l in /nix/var/nix/profiles/system-*-link; do
              if [ "$(${pkgs.coreutils}/bin/readlink -f "$l")" = "$booted" ]; then
                gen=$(${pkgs.coreutils}/bin/basename "$l" | ${pkgs.gnugrep}/bin/grep -oE '[0-9]+')
                break
              fi
            done
            "$HOME/.bin/notify-pushover" "Booted minix: ''${ver} | kernel $(${pkgs.coreutils}/bin/uname -r) | gen ''${gen:-?} | $(${pkgs.coreutils}/bin/date +%Y-%m-%dT%H:%M)"
          '';
        in
        "${bootNotify}";
      ExecStartPost = "${pkgs.coreutils}/bin/touch /run/user/%U/boot-notify-done";
      Environment = "PATH=${pkgs.bash}/bin:${pkgs.coreutils}/bin:${pkgs.curl}/bin";
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.friday-ruler = mkProjectService {
    dir = "friday-ruler";
    description = "Friday Ruler";
    extraUnits = [ "sops-nix.service" ];
    needsMqtt = true;
    build = "npm run build";
    command = "node dist/src/main.js";
    timeoutStop = 10;
  };

  systemd.user.services.xiaomiclock2mqtt = mkProjectService {
    dir = "xiaomiclock2mqtt";
    description = "Xiaomi Clock BLE to MQTT Bridge";
    needsMqtt = true;
    build = "npm run build";
    command = "node dist/index.js";
    oneshot = true;
    timeoutStart = "10min";
  };

  systemd.user.timers.xiaomiclock2mqtt = mkTimer {
    description = "Xiaomi Clock BLE poll timer";
    onCalendar = "*:0/30";
  };

  systemd.user.services.timav-cache = mkProjectService {
    dir = "timav";
    description = "Timav cache update";
    extraUnits = [ "sops-nix.service" ];
    command = "./cli.js cache";
    environment = "DEBUG=*";
    oneshot = true;
    timeoutStart = "10min";
  };

  systemd.user.timers.timav-cache = mkTimer {
    description = "Timav cache update timer";
    onCalendar = "hourly";
  };

  systemd.user.services.szymonkaliski-com-publish = mkProjectService {
    dir = "szymonkaliski-com";
    description = "Publish szymonkaliski.com";
    command = "bash -c './scripts/update-notes.sh && ./scripts/publish.sh'";
    oneshot = true;
    timeoutStart = "10min";
    environment = [
      "WIKI_PATH=%h/Dropbox/Wiki"
      "PATH=${
        pkgs.lib.makeBinPath [
          pkgs.ripgrep
          pkgs.rsync
          pkgs.git
          pkgs.openssh
          pkgs.coreutils
          pkgs.bash
          pkgs.nix
        ]
      }:%h/.bin"
    ];
  };

  systemd.user.timers.szymonkaliski-com-publish = mkTimer {
    description = "Weekly publish of szymonkaliski.com";
    onCalendar = "Mon *-*-* 01:00:00";
  };

  systemd.user.services.archivist-fetch = mkProjectService {
    dir = "archivist";
    description = "Archivist fetch";
    extraUnits = [ "sops-nix.service" ];
    command = "node dist/cli/index.js fetch";
    oneshot = true;
    timeoutStart = "60min";
  };

  systemd.user.timers.archivist-fetch = mkTimer {
    description = "Archivist fetch timer";
    onCalendar = "hourly";
  };

  systemd.user.services.archivist-web-ui = mkProjectService {
    dir = "archivist";
    description = "Archivist web UI";
    extraUnits = [ "sops-nix.service" ];
    build = "npm run build";
    command = "node dist/server/index.js";
    environment = "PORT=${toString ports.archivistUi}";
    successExitStatus = "143";
    timeoutStop = 10;
  };

  # tmux.service owns creating the "home" session; start after it so home
  # exists before telegraphist attaches (telegraphist only recreates home as a watchdog)
  systemd.user.services.telegraphist = mkProjectService {
    dir = "telegraphist";
    description = "Telegraphist terminal";
    extraUnits = [ "tmux.service" ];
    build = "npm run build";
    command = "${pkgs.bash}/bin/bash -c 'SHELL=${pkgs.zsh}/bin/zsh PATH=%h/.bin:${pkgs.tmux}/bin:$PATH exec node dist/server/server.js'";
    environment = "PORT=${toString ports.telegraphist}";
    successExitStatus = "143";
    timeoutStop = 10;
    extraService = {
      # https:// through tailscale serve
      ExecStartPost = "${pkgs.tailscale}/bin/tailscale serve --bg --https=${toString ports.telegraphist} ${toString ports.telegraphist}";
      ExecStopPost = "${pkgs.tailscale}/bin/tailscale serve --https=${toString ports.telegraphist} off";
    };
  };

  systemd.user.services.healthcheck = {
    Unit = {
      Description = "System healthcheck";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
    };

    Service = {
      Type = "oneshot";
      TimeoutStartSec = "10min";
      ExecStart = "${pkgs.bash}/bin/bash %h/.bin/healthcheck";
      Environment = "PATH=/run/wrappers/bin:/run/current-system/sw/bin:%h/.nix-profile/bin:%h/.bin";
    };
  };

  systemd.user.timers.healthcheck = mkTimer {
    description = "Daily system healthcheck";
    onCalendar = "*-*-* 08:00:00";
  };

  systemd.user.services.rss2email = {
    Unit = {
      Description = "RSS to email";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
    };

    Service = {
      Type = "oneshot";
      TimeoutStartSec = "10min";
      ExecStart = "${pkgs.rss2email}/bin/r2e run";
      Environment = "PATH=${pkgs.msmtp}/bin";
    };
  };

  systemd.user.timers.rss2email = mkTimer {
    description = "RSS to email check";
    onCalendar = "*-*-* 00/6:00:00";
  };

  systemd.user.services.property-search = mkProjectService {
    dir = "property-search";
    description = "Property Search web UI";
    extraUnits = [ "sops-nix.service" ];
    build = "npm run build";
    command = "node dist/index.js";
    environment = "PORT=${toString ports.propertySearch}";
    successExitStatus = "143";
    timeoutStop = 10;
  };

  systemd.user.services.property-search-scrape = mkProjectService {
    dir = "property-search";
    description = "Property Search scraper";
    extraUnits = [ "sops-nix.service" ];
    command = "npm run scrape";
    oneshot = true;
    timeoutStart = "60min";
  };

  systemd.user.timers.property-search-scrape = mkTimer {
    description = "Nightly Property Search scrape";
    onCalendar = "*-*-* 01:00:00";
  };

  systemd.user.services.trash-empty = {
    Unit = {
      Description = "Purge trashed files older than 90 days";
    };

    Service = {
      Type = "oneshot";
      TimeoutStartSec = "10min";
      ExecStart = "${pkgs.trash-cli}/bin/trash-empty 90";
    };
  };

  systemd.user.timers.trash-empty = mkTimer {
    description = "Daily trash cleanup";
    onCalendar = "daily";
  };

  xdg.configFile."timav-nodejs/config.json".source = link "${dotfileDir}/timav/config.json";

  sops.templates."timav-credentials.json" = {
    path = "${config.home.homeDirectory}/.config/timav-nodejs/credentials.json";
    content = builtins.toJSON {
      installed = {
        client_id = config.sops.placeholder.timav_google_client_id;
        project_id = config.sops.placeholder.timav_google_project_id;
        auth_uri = "https://accounts.google.com/o/oauth2/auth";
        token_uri = "https://oauth2.googleapis.com/token";
        auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs";
        client_secret = config.sops.placeholder.timav_google_client_secret;
        redirect_uris = [
          "urn:ietf:wg:oauth:2.0:oob"
          "http://localhost"
        ];
      };
    };
  };

}
