{
  config,
  pkgs,
  repoRoot,
  ...
}:
let
  dotfileDir = "${repoRoot}/dotfiles";
  link = config.lib.file.mkOutOfStoreSymlink;
  mqtt = import ../../mqtt.nix;
  neolink = pkgs.callPackage ../../pkgs/neolink.nix { };
  waitForMosquitto = pkgs.writeShellScript "wait-for-mosquitto" ''
    for i in {1..30}; do
      ${pkgs.mosquitto}/bin/mosquitto_pub \
        -h ${mqtt.host} -p ${toString mqtt.port} \
        -u ${mqtt.username} -P ${mqtt.password} \
        -t healthcheck/wait -m ping -q 0 \
        2>/dev/null && exit 0
      sleep 1
    done
    echo "mosquitto not ready"
    exit 1
  '';

in
{
  imports = [ ../../common.nix ];

  home.homeDirectory = "/home/szymon";

  sops.defaultSopsFile = ../../secrets/minix.yaml;
  sops.age.keyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt";

  sops.secrets.claude_oauth_token = { };
  sops.secrets.smartbox_email = { };
  sops.secrets.smartbox_password = { };
  sops.secrets.neolink_cam_1_username = { };
  sops.secrets.neolink_cam_2_username = { };
  sops.secrets.neolink_hallway_1_username = { };
  sops.secrets.neolink_hallway_2_username = { };
  sops.secrets.neolink_cam_1_password = { };
  sops.secrets.neolink_cam_2_password = { };
  sops.secrets.neolink_hallway_1_password = { };
  sops.secrets.neolink_hallway_2_password = { };
  sops.secrets.neolink_cam_1_uid = { };
  sops.secrets.neolink_cam_2_uid = { };
  sops.secrets.neolink_hallway_1_uid = { };
  sops.secrets.neolink_hallway_2_uid = { };
  sops.secrets.archivist_pinterest_email = { };
  sops.secrets.archivist_pinterest_password = { };
  sops.secrets.archivist_pinboard_api_key = { };
  sops.secrets.archivist_arena_access_token = { };
  sops.secrets.smtp_host = { };
  sops.secrets.smtp_bot_email = { };
  sops.secrets.smtp_bot_password = { };
  sops.secrets.gemini_api_key_property_search = { };
  sops.secrets.pushover_token_user = { };
  sops.secrets.pushover_user = { };

  # token generated by `claude setup-token`
  sops.templates."claude-oauth-token" = {
    path = "${config.home.homeDirectory}/.claude/long-lived-oauth-token";
    content = config.sops.placeholder.claude_oauth_token;
  };

  sops.templates."smartbox2mqtt-config" = {
    path = "${config.home.homeDirectory}/.config/smartbox2mqtt/config.json";
    content = builtins.toJSON {
      smartbox = {
        username = config.sops.placeholder.smartbox_email;
        password = config.sops.placeholder.smartbox_password;
        apiName = "api-hjm";
      };
      mqtt = {
        host = mqtt.host;
        port = mqtt.port;
        username = mqtt.username;
        password = mqtt.password;
        baseTopic = "friday/hjm";
      };
    };
  };

  sops.templates."neolink-config" = {
    path = "${config.home.homeDirectory}/.config/neolink/config.toml";
    content = ''
      bind = "0.0.0.0"

      [mqtt]
      broker_addr = "${mqtt.host}"
      port = ${toString mqtt.port}
      credentials = ["${mqtt.username}", "${mqtt.password}"]

      [[cameras]]
      name = "cam_1"
      username = "${config.sops.placeholder.neolink_cam_1_username}"
      password = "${config.sops.placeholder.neolink_cam_1_password}"
      uid = "${config.sops.placeholder.neolink_cam_1_uid}"
      idle_disconnect = true
      [cameras.mqtt]
      enable_motion = true
      enable_battery = true
      battery_update = 21600000
      enable_light = false
      enable_preview = false
      enable_floodlight = false

      [[cameras]]
      name = "cam_2"
      username = "${config.sops.placeholder.neolink_cam_2_username}"
      password = "${config.sops.placeholder.neolink_cam_2_password}"
      uid = "${config.sops.placeholder.neolink_cam_2_uid}"
      idle_disconnect = true
      [cameras.mqtt]
      enable_motion = true
      enable_battery = true
      battery_update = 21600000
      enable_light = false
      enable_preview = false
      enable_floodlight = false

      [[cameras]]
      name = "hallway_1"
      username = "${config.sops.placeholder.neolink_hallway_1_username}"
      password = "${config.sops.placeholder.neolink_hallway_1_password}"
      uid = "${config.sops.placeholder.neolink_hallway_1_uid}"
      idle_disconnect = true
      [cameras.mqtt]
      enable_motion = true
      enable_battery = true
      battery_update = 21600000
      enable_light = false
      enable_preview = false
      enable_floodlight = false

      [[cameras]]
      name = "hallway_2"
      username = "${config.sops.placeholder.neolink_hallway_2_username}"
      password = "${config.sops.placeholder.neolink_hallway_2_password}"
      uid = "${config.sops.placeholder.neolink_hallway_2_uid}"
      idle_disconnect = true
      [cameras.mqtt]
      enable_motion = true
      enable_battery = true
      battery_update = 21600000
      enable_light = false
      enable_preview = false
      enable_floodlight = false
    '';
  };

  sops.templates."friday-ruler-config" = {
    path = "${config.home.homeDirectory}/.config/friday-ruler/config.json";
    content = builtins.toJSON {
      mqtt = {
        host = mqtt.host;
        port = mqtt.port;
        username = mqtt.username;
        password = mqtt.password;
      };
      pushover = {
        token = config.sops.placeholder.pushover_token_user;
        user = config.sops.placeholder.pushover_user;
      };
      router = {
        host = "192.168.1.1";
        username = "admin";
        privateKeyPath = "${config.home.homeDirectory}/.ssh/id_ed25519";
      };
      location = {
        lat = 52.4069;
        lon = 16.9299;
      };
    };
  };

  sops.templates."archivist-config" = {
    path = "${config.home.homeDirectory}/.config/archivist/config.json";
    content = builtins.toJSON {
      pinterest = {
        loginMethod = "password";
        profile = "szymon_k";
        username = config.sops.placeholder.archivist_pinterest_email;
        password = config.sops.placeholder.archivist_pinterest_password;
        appendOnly = true;
      };
      pinboard = {
        apiKey = config.sops.placeholder.archivist_pinboard_api_key;
      };
      arena = {
        userId = 52291;
        accessToken = config.sops.placeholder.archivist_arena_access_token;
      };
      screenshot = {
        directory = "${config.home.homeDirectory}/.dropbox-hm/Dropbox/Screenshots";
      };
    };
  };

  sops.templates."msmtp-config" = {
    path = "${config.home.homeDirectory}/.config/msmtp/config";
    content = ''
      defaults
      tls on
      port 587

      account default
      host ${config.sops.placeholder.smtp_host}
      from ${config.sops.placeholder.smtp_bot_email}
      auth on
      user ${config.sops.placeholder.smtp_bot_email}
      password ${config.sops.placeholder.smtp_bot_password}
    '';
  };

  sops.templates."property-search-config.json" = {
    path = "${config.home.homeDirectory}/.config/property-search/config.json";
    content = builtins.toJSON {
      smtp = {
        host = config.sops.placeholder.smtp_host;
        port = 587;
        user = config.sops.placeholder.smtp_bot_email;
        pass = config.sops.placeholder.smtp_bot_password;
      };
      email = {
        from = "Property Search Bot <${config.sops.placeholder.smtp_bot_email}>";
        to = "hi@szymonkaliski.com";
      };
      gemini = {
        apiKey = config.sops.placeholder.gemini_api_key_property_search;
      };
    };
  };

  sops.templates."pushoverrc" = {
    path = "${config.home.homeDirectory}/.pushoverrc";
    content = ''
      PUSHOVER_TOKEN=${config.sops.placeholder.pushover_token_user}
      PUSHOVER_USER=${config.sops.placeholder.pushover_user}
    '';
  };

  home.packages = [
    neolink
    pkgs.chromium
    pkgs.dnsutils
    pkgs.lm_sensors
    pkgs.trash-cli
  ];

  home.file.".config/rss2email.cfg".source = link "${dotfileDir}/rss2email.cfg";

  xdg.configFile."lgtv2mqtt2/lgtv.json".source = link "${dotfileDir}/lgtv2mqtt2/lgtv.json";

  xdg.configFile."lgtv2mqtt2/mqtt.json".text = builtins.toJSON {
    host = mqtt.host;
    username = mqtt.username;
    password = mqtt.password;
  };

  xdg.configFile."xiaomiclock2mqtt/config.json".text = builtins.toJSON {
    ble = {
      mac = "A4:C1:38:B3:76:F7";
    };
    mqtt = {
      host = mqtt.host;
      port = mqtt.port;
      username = mqtt.username;
      password = mqtt.password;
      baseTopic = "friday/sensor_living_room_temperature";
    };
  };

  services.dropbox.enable = true;

  # auto-start default "home" session in tmux
  systemd.user.services.tmux = {
    Unit = {
      Description = "tmux default session";
      # don't restart on rebuild (kills running sessions)
      X-SwitchMethod = "keep-old";
    };
    Service = {
      Type = "forking";
      ExecStart = "${pkgs.zsh}/bin/zsh -lc '${pkgs.tmux}/bin/tmux new-session -s home -d'";
      ExecStop = "${pkgs.tmux}/bin/tmux kill-server";
      Restart = "always";
    };
    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.dropbox.Unit.OnFailure = [ "notify-failure@%N.service" ];

  systemd.user.services."notify-failure@" = {
    Unit.Description = "Failure notification for %i";
    Service = {
      Type = "oneshot";
      # wait for possible restart, skip if service recovered
      ExecStartPre = "${pkgs.coreutils}/bin/sleep 5";
      ExecCondition = "${pkgs.bash}/bin/bash -c '! ${pkgs.systemd}/bin/systemctl --user is-active --quiet %i'";
      ExecStart = "-${pkgs.bash}/bin/bash -c '%h/.bin/notify-pushover \"Failed: %i\"'";
      Environment = "PATH=${pkgs.bash}/bin:${pkgs.coreutils}/bin:${pkgs.curl}/bin";
    };
  };

  systemd.user.services.neolink = {
    Unit = {
      Description = "Neolink MQTT bridge for Reolink cameras";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
    };

    Service = {
      ExecStartPre = waitForMosquitto;
      ExecStart = "${neolink}/bin/neolink mqtt --config=%h/.config/neolink/config.toml";
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.smartbox2mqtt = {
    Unit = {
      Description = "Smartbox to MQTT bridge for heaters";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/smartbox2mqtt";
    };

    Service = {
      ExecStartPre = waitForMosquitto;
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/smartbox2mqtt --command node src/index.js";
      WorkingDirectory = "%h/Projects/smartbox2mqtt";
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.lgtv2mqtt2 = {
    Unit = {
      Description = "LG TV to MQTT bridge";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/lgtv2mqtt2";
    };

    Service = {
      ExecStartPre = waitForMosquitto;
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/lgtv2mqtt2 --command node cli.js";
      WorkingDirectory = "%h/Projects/lgtv2mqtt2";
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.friday-homebridge = {
    Unit = {
      Description = "Homebridge";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/friday-homebridge";
    };

    Service = {
      ExecStartPre = [
        waitForMosquitto
        "${pkgs.nix}/bin/nix develop %h/Projects/friday-homebridge --command npm run pre-run"
      ];
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/friday-homebridge --command npx homebridge -I";
      WorkingDirectory = "%h/Projects/friday-homebridge";
      # homebridge exits 143 (SIGTERM) on clean stop
      SuccessExitStatus = "143";
      TimeoutStopSec = 10;
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.boot-notify = {
    Unit = {
      Description = "Boot notification";
      After = [
        "default.target"
        "network-online.target"
      ];
      Wants = [ "network-online.target" ];
      ConditionPathExists = "!/run/user/%U/boot-notify-done";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash -c '%h/.bin/notify-pushover \"Booted: $(date +%%Y-%%m-%%dT%%H:%%M)\"'";
      ExecStartPost = "${pkgs.coreutils}/bin/touch /run/user/%U/boot-notify-done";
      Environment = "PATH=${pkgs.bash}/bin:${pkgs.coreutils}/bin:${pkgs.curl}/bin";
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.friday-ruler = {
    Unit = {
      Description = "Friday Ruler";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/friday-ruler";
    };

    Service = {
      ExecStartPre = [
        waitForMosquitto
        "${pkgs.nix}/bin/nix develop %h/Projects/friday-ruler --command npm run build"
      ];
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/friday-ruler --command node dist/main.js";
      WorkingDirectory = "%h/Projects/friday-ruler";
      TimeoutStopSec = 10;
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.xiaomiclock2mqtt = {
    Unit = {
      Description = "Xiaomi Clock BLE to MQTT Bridge";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/xiaomiclock2mqtt";
    };

    Service = {
      Type = "oneshot";
      ExecStartPre = [
        waitForMosquitto
        "${pkgs.nix}/bin/nix develop %h/Projects/xiaomiclock2mqtt --command npm run build"
      ];
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/xiaomiclock2mqtt --command node dist/index.js";
      WorkingDirectory = "%h/Projects/xiaomiclock2mqtt";
    };
  };

  systemd.user.timers.xiaomiclock2mqtt = {
    Unit = {
      Description = "Xiaomi Clock BLE poll timer";
    };

    Timer = {
      OnCalendar = "*:0/30";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.timav-cache = {
    Unit = {
      Description = "Timav cache update";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/timav";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/timav --command ./cli.js cache";
      WorkingDirectory = "%h/Projects/timav";
      Environment = "DEBUG=*";
    };
  };

  systemd.user.timers.timav-cache = {
    Unit = {
      Description = "Timav cache update timer";
    };

    Timer = {
      OnCalendar = "hourly";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.szymonkaliski-com-publish = {
    Unit = {
      Description = "Publish szymonkaliski.com";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/szymonkaliski-com";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/szymonkaliski-com --command bash -c './scripts/update-notes.sh && ./scripts/publish.sh'";
      WorkingDirectory = "%h/Projects/szymonkaliski-com";
      Environment = [
        "WIKI_PATH=%h/Dropbox/Wiki"
        "PATH=${
          pkgs.lib.makeBinPath [
            pkgs.ripgrep
            pkgs.rsync
            pkgs.git
            pkgs.openssh
            pkgs.coreutils
            pkgs.bash
            pkgs.nix
          ]
        }:%h/.bin"
      ];
    };
  };

  systemd.user.timers.szymonkaliski-com-publish = {
    Unit = {
      Description = "Weekly publish of szymonkaliski.com";
    };

    Timer = {
      OnCalendar = "Mon *-*-* 01:00:00";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.archivist-fetch = {
    Unit = {
      Description = "Archivist fetch";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/archivist";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/archivist --command node dist/cli/index.js fetch";
      WorkingDirectory = "%h/Projects/archivist";
    };
  };

  systemd.user.timers.archivist-fetch = {
    Unit = {
      Description = "Archivist fetch timer";
    };

    Timer = {
      OnCalendar = "hourly";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.archivist-web-ui = {
    Unit = {
      Description = "Archivist web UI";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/archivist";
    };

    Service = {
      ExecStartPre = "${pkgs.nix}/bin/nix develop %h/Projects/archivist --command npm run build";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/archivist --command node dist/server/index.js";
      WorkingDirectory = "%h/Projects/archivist";
      Environment = "PORT=10005";
      SuccessExitStatus = "143";
      TimeoutStopSec = 10;
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.web-tty = {
    Unit = {
      Description = "Web TTY terminal";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/web-tty";
    };

    Service = {
      ExecStartPre = "${pkgs.nix}/bin/nix develop %h/Projects/web-tty --command npm run build";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/web-tty --command ${pkgs.bash}/bin/bash -c 'SHELL=${pkgs.zsh}/bin/zsh PATH=%h/.bin:$PATH exec node dist/server/server.js motd'";

      # https:// through tailscale serve
      ExecStartPost = "${pkgs.tailscale}/bin/tailscale serve --bg --https=10006 10006";
      ExecStopPost = "${pkgs.tailscale}/bin/tailscale serve --https=10006 off";

      WorkingDirectory = "%h/Projects/web-tty";
      Environment = "PORT=10006";
      SuccessExitStatus = "143";
      TimeoutStopSec = 10;
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.healthcheck = {
    Unit = {
      Description = "System healthcheck";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash %h/.bin/healthcheck";
      Environment = "PATH=/run/wrappers/bin:/run/current-system/sw/bin:%h/.nix-profile/bin:%h/.bin";
    };
  };

  systemd.user.timers.healthcheck = {
    Unit = {
      Description = "Daily system healthcheck";
    };

    Timer = {
      OnCalendar = "*-*-* 08:00:00";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.rss2email = {
    Unit = {
      Description = "RSS to email";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.rss2email}/bin/r2e run";
      Environment = "PATH=${pkgs.msmtp}/bin";
    };
  };

  systemd.user.timers.rss2email = {
    Unit = {
      Description = "RSS to email check";
    };

    Timer = {
      OnCalendar = "*-*-* 00/6:00:00";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.property-search = {
    Unit = {
      Description = "Property Search web UI";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/property-search";
    };

    Service = {
      ExecStartPre = "${pkgs.nix}/bin/nix develop %h/Projects/property-search --command npm run build";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/property-search --command node dist/index.js";
      WorkingDirectory = "%h/Projects/property-search";
      Environment = "PORT=10007";
      SuccessExitStatus = "143";
      TimeoutStopSec = 10;
      Restart = "on-failure";
      RestartSec = 30;
    };

    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  systemd.user.services.property-search-scrape = {
    Unit = {
      Description = "Property Search scraper";
      After = [
        "network-online.target"
        "sops-nix.service"
      ];
      Wants = [
        "network-online.target"
        "sops-nix.service"
      ];
      OnFailure = [ "notify-failure@%N.service" ];
      ConditionPathIsDirectory = "%h/Projects/property-search";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.nix}/bin/nix develop %h/Projects/property-search --command npm run scrape";
      WorkingDirectory = "%h/Projects/property-search";
    };
  };

  systemd.user.timers.property-search-scrape = {
    Unit = {
      Description = "Nightly Property Search scrape";
    };

    Timer = {
      OnCalendar = "*-*-* 01:00:00";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  systemd.user.services.trash-empty = {
    Unit = {
      Description = "Purge trashed files older than 90 days";
    };

    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.trash-cli}/bin/trash-empty 90";
    };
  };

  systemd.user.timers.trash-empty = {
    Unit = {
      Description = "Daily trash cleanup";
    };

    Timer = {
      OnCalendar = "daily";
      Persistent = true;
    };

    Install = {
      WantedBy = [ "timers.target" ];
    };
  };

  xdg.configFile."timav-nodejs/config.json".source = link "${dotfileDir}/timav/config.json";

  sops.secrets.timav_google_client_id = {
    sopsFile = ../../secrets/shared.yaml;
  };
  sops.secrets.timav_google_client_secret = {
    sopsFile = ../../secrets/shared.yaml;
  };
  sops.secrets.timav_google_project_id = {
    sopsFile = ../../secrets/shared.yaml;
  };

  sops.templates."timav-credentials.json" = {
    path = "${config.home.homeDirectory}/.config/timav-nodejs/credentials.json";
    content = builtins.toJSON {
      installed = {
        client_id = config.sops.placeholder.timav_google_client_id;
        project_id = config.sops.placeholder.timav_google_project_id;
        auth_uri = "https://accounts.google.com/o/oauth2/auth";
        token_uri = "https://oauth2.googleapis.com/token";
        auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs";
        client_secret = config.sops.placeholder.timav_google_client_secret;
        redirect_uris = [
          "urn:ietf:wg:oauth:2.0:oob"
          "http://localhost"
        ];
      };
    };
  };

}
